In [1]:
import pandas as pd

In [5]:
# 2 main datatypes
series = pd.Series(["BMW", "Toyota", "Honda"])

In [6]:
series

0       BMW
1    Toyota
2     Honda
dtype: str

In [7]:
# series = 1-dimensional

In [8]:
colours = pd.Series(["Red", "Blue", "Green"])
colours

0      Red
1     Blue
2    Green
dtype: str

In [9]:
# DataFrame = 2-dimesnional
car_data = pd.DataFrame({"Car make": series, "Color": colours})
car_data

  Car make  Color
0      BMW    Red
1   Toyota   Blue
2    Honda  Green

In [10]:
# Import data
car_sales = pd.read_csv("car-sales.csv")

In [11]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [12]:
# Exporting a dataframe
car_sales.to_csv("exported-car-sales.csv")

In [14]:
exported_car_sales = pd.read_csv("exported-car-sales.csv")
exported_car_sales

   Unnamed: 0    Make Colour  Odometer (KM)  Doors       Price
0           0  Toyota  White         150043      4   $4,000.00
1           1   Honda    Red          87899      4   $5,000.00
2           2  Toyota   Blue          32549      3   $7,000.00
3           3     BMW  Black          11179      5  $22,000.00
4           4  Nissan  White         213095      4   $3,500.00
5           5  Toyota  Green          99213      4   $4,500.00
6           6   Honda   Blue          45698      4   $7,500.00
7           7   Honda   Blue          54738      4   $7,000.00
8           8  Toyota  White          60000      4   $6,250.00
9           9  Nissan  White          31600      4   $9,700.00

In [15]:
car_sales.to_csv("exported-car-sales-2.csv", index=False)

In [16]:
exported_car_sales = pd.read_csv("exported-car-sales-2.csv")
exported_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

## Describe data

In [17]:
# Attribute
car_sales.dtypes

# Funtion
# car_sales.to_csv()

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

In [18]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [19]:
car_columns = car_sales.columns
car_columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [20]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [21]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [22]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [23]:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [26]:
car_sales.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

In [27]:
car_prices = pd.Series([3000, 1500, 111250])
car_prices.mean()

np.float64(38583.333333333336)

In [28]:
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [29]:
car_sales["Doors"].sum()

np.int64(40)

In [30]:
len(car_sales)

10

In [31]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00